name: Nightly tests

on:
  schedule:
    - cron: '4 4 * * *'

env:
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 3

jobs:
  unit:
    if: github.repository == 'theforeman/puppet-foreman_proxy_content'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5"
          - "2.4"
        puppet:
          - "6"
          - "5"
        exclude:
          - ruby: "2.5"
            puppet: "5"
          - ruby: "2.4"
            puppet: "6"
    env:
      BUNDLE_WITHOUT: development:system_tests
      PUPPET_VERSION: "${{ matrix.puppet }}.0"
    name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.puppet }}-${{ matrix.ruby }}-gems-unit-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.puppet }}-${{ matrix.ruby }}-gems-unit-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          bundle clean
      - name: Run tests
        run: bundle exec rake

  setup_matrix:
    name: 'Setup Test Matrix'
    if: github.repository == 'theforeman/puppet-foreman_proxy_content'
    runs-on: ubuntu-latest
    outputs:
      setfiles: ${{ steps.get-setfiles.outputs.setfiles }}
      puppet_major_versions: ${{ steps.get-setfiles.outputs.puppet_major_versions }}
    env:
      BUNDLE_WITHOUT: development:test
    steps:
      - name: Enable IPv6 on docker
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-2.7-gems-acceptance-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-2.7-gems-acceptance-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          bundle clean
      - name: Setup Acceptance Test Matrix
        id: get-setfiles
        run: bundle exec metadata2gha-beaker --use-fqdn --pidfile-workaround false

  acceptance:
    if: github.repository == 'theforeman/puppet-foreman_proxy_content'
    needs: build_cache
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development:test
    strategy:
      fail-fast: false
      matrix:
        setfile: ${{fromJson(needs.setup_matrix.outputs.setfiles)}}
        puppet: ${{fromJson(needs.setup_matrix.outputs.puppet_major_versions)}}
        puppet:
          - "6"
          - "5"
    name: Puppet ${{ matrix.puppet }} - ${{ matrix.setfile.name }}
    steps:
      - name: Enable IPv6 on docker
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-2.7-gems-acceptance-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-2.7-gems-acceptance-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: bundle exec rake beaker
        env:
          BEAKER_PUPPET_COLLECTION: puppet${{ matrix.puppet }}
          BEAKER_setfile: ${{ matrix.setfile.value }}
